### ISSUE TITLE
when I execute yarn build,  I met a problem

### ISSUE THREAD

**Issue by smilery37** [Microsoft/charticulator#105]
I went to the step -- yarn build, but after the code had been executed, I met the problems as follows:
_yarn run v1.10.1
$ node build.js --mode=production
charticulator/build.js:30
async function addHASHToHTMLs() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
error Command failed with exit code 1._

I didn't get enough infos,    what should I do?

**Comment by smilery37** [comment]
sorry,  I think it's maybe about the version of nodejs  I did neglect.
