### ISSUE TITLE
expanding "symbol 1" menu in PBI brings up error 

### ISSUE THREAD

**Issue by snapper911T** [microsoft/charticulator#234]
When expanding the symbol option i get the below error:

![image](https://user-images.githubusercontent.com/43861167/82013950-64164880-9630-11ea-8301-9c70f3e4565c.png)

Feedback Type:
Frown (Error)

Error Message:
An error occurred while rendering the report.

Stack Trace:
(at Error: [$parse:syntax] Syntax Error: Token 'vll1fhkz69' is an unexpected token at column 64 of the expression [CHARTICULATOR_VISUAL_MyVisual2D8730A9416EF4EC187A897D1A2D6224-7vll1fhkz69-form] starting at [vll1fhkz69-form].
http://errors.angularjs.org/1.6.8/$parse/syntax?p0=vll1fhkz69&p1=is%20an%20unexpected%20token&p2=64&p3=CHARTICULATOR_VISUAL_MyVisual2D8730A9416EF4EC187A897D1A2D6224-7vll1fhkz69-form&p4=vll1fhkz69-form (caused by "<form ng-if="$ctrl.expanded" name="{{$ctrl.viewModel.id}}-form" class="contents ng-pristine ng-valid" id="content-{{$ctrl.viewModel.id}}" aria-labelledby="title-{{$ctrl.viewModel.id}}" aria-hidden="{{!$ctrl.expanded}}">")
    at ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:143:12
    at AST.throwError (ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:15380:11)
    at AST.ast (ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:15130:12)
    at Parser.getAst (ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:16489:21)
    at Parser.parse (ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:16472:20)
    at $parse (ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:16630:39)
    at getSetter (ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:23894:14)
    at Object.ngFormPreLink (ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:23865:37)
    at ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:1410:18
    at invokeLinkFn (ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:10641:9):line:null:)
Error: [$parse:syntax] Syntax Error: Token 'vll1fhkz69' is an unexpected token at column 64 of the expression [CHARTICULATOR_VISUAL_MyVisual2D8730A9416EF4EC187A897D1A2D6224-7vll1fhkz69-form] starting at [vll1fhkz69-form].
http://errors.angularjs.org/1.6.8/$parse/syntax?p0=vll1fhkz69&p1=is%20an%20unexpected%20token&p2=64&p3=CHARTICULATOR_VISUAL_MyVisual2D8730A9416EF4EC187A897D1A2D6224-7vll1fhkz69-form&p4=vll1fhkz69-form (caused by "<form ng-if="$ctrl.expanded" name="{{$ctrl.viewModel.id}}-form" class="contents ng-pristine ng-valid" id="content-{{$ctrl.viewModel.id}}" aria-labelledby="title-{{$ctrl.viewModel.id}}" aria-hidden="{{!$ctrl.expanded}}">")
    at ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:143:12
    at AST.throwError (ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:15380:11)
    at AST.ast (ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:15130:12)
    at Parser.getAst (ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:16489:21)
    at Parser.parse (ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:16472:20)
    at $parse (ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:16630:39)
    at getSetter (ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:23894:14)
    at Object.ngFormPreLink (ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:23865:37)
    at ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:1410:18
    at invokeLinkFn (ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:10641:9)

Stack Trace Message:
An error occurred while rendering the report.

Invocation Stack Trace:
   at Microsoft.Mashup.Host.Document.ExceptionExtensions.GetCurrentInvocationStackTrace()
   at Microsoft.Mashup.Client.UI.Shared.StackTraceInfo..ctor(String exceptionStackTrace, String invocationStackTrace, String exceptionMessage)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.GetStackTraceInfo(Exception e)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.ReportException(IWindowHandle activeWindow, IUIHost uiHost, FeedbackPackageInfo feedbackPackageInfo, Exception e, Boolean useGDICapture)
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.<>c__DisplayClass14_0.<HandleException>b__0()
   at Microsoft.Mashup.Host.Document.SynchronizationContextExtensions.<>c__DisplayClass0_1.<SendAndMarshalExceptions>b__0(Object null)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Microsoft.Mashup.Client.UI.Shared.WebDialogs.WebDialog.<>n__0(IWindowHandle owner)
   at Microsoft.Mashup.Client.UI.Shared.WindowManager.ShowModal[T](T dialog, Func`1 showModalFunction)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClass2_0.<Main>b__1()
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<>c__DisplayClass3_0.<HandleExceptionsWithNestedTasks>b__0()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Program.Main(String[] args)

JS Error Message:
[$parse:syntax] Syntax Error: Token 'vll1fhkz69' is an unexpected token at column 64 of the expression [CHARTICULATOR_VISUAL_MyVisual2D8730A9416EF4EC187A897D1A2D6224-7vll1fhkz69-form] starting at [vll1fhkz69-form].
http://errors.angularjs.org/1.6.8/$parse/syntax?p0=vll1fhkz69&p1=is%20an%20unexpected%20token&p2=64&p3=CHARTICULATOR_VISUAL_MyVisual2D8730A9416EF4EC187A897D1A2D6224-7vll1fhkz69-form&p4=vll1fhkz69-form (caused by "<form ng-if="$ctrl.expanded" name="{{$ctrl.viewModel.id}}-form" class="contents ng-pristine ng-valid" id="content-{{$ctrl.viewModel.id}}" aria-labelledby="title-{{$ctrl.viewModel.id}}" aria-hidden="{{!$ctrl.expanded}}">")

PowerBINonFatalError:
{"AppName":"PBIDesktop","AppVersion":"2.80.5803.1061","ModuleName":"ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js","Component":"","Error":"Error","MethodDef":"","ErrorOffset":"143:12"}

Snapshot Trace Logs:
C:\Users\snapp\AppData\Local\Microsoft\Power BI Desktop\FrownSnapShot793437405.zip

Model Default Mode:
Import

Model Version:
PowerBI_V1

Is Report V3 Models Enabled:
False

Performance Trace Logs:
C:\Users\snapp\AppData\Local\Microsoft\Power BI Desktop\PerformanceTraces.zip

Enabled Preview Features:
PBI_NewWebTableInference
PBI_inlineExplore
PBI_realTimeRefresh
PBI_showMinervaRibbon
PBI_showMinervaViewNavigator
PBI_decompositionTree
PBI_hierarchicalSlicerCreation
PBI_relativeTimeSlicer

Disabled Preview Features:
PBI_shapeMapVisualEnabled
PBI_SpanishLinguisticsEnabled
PBI_qnaLiveConnect
PQ_AIInsightsFunctionBrowser
PBI_v3ModelsPreview

Disabled DirectQuery Options:
TreatHanaAsRelationalSource

Cloud:
GlobalCloud

Recent Actions:
VisualContainerUpdateDimensions, SavePropertyPane, SavePropertyPane, SavePropertyPane, CreateSection, SetSectionType, setCrossReportDrillthrough, UpdateCanvasDimension, AddVisualContainer, AddFieldInRole, VisualConversion, SavePropertyPane, SavePropertyPane, SavePropertyPane, SavePropertyPane

Formulas:

section Section1;

shared vehicles = let
    Source = Csv.Document(File.Contents("C:\Users\snapp\Documents\datasets\Star Wars\vehicles.csv"),[Delimiter=",", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"name", type text}, {"model", type text}, {"manufacturer", type text}, {"cost_in_credits", type text}, {"length", type text}, {"max_atmosphering_speed", type text}, {"crew", Int64.Type}, {"passengers", type text}, {"cargo_capacity", type text}, {"consumables", type text}, {"vehicle_class", type text}})
in
    #"Changed Type";

Active Section Contract:
{"id":0,"name":"ReportSection","displayName":"Page 1","filters":"[]","ordinal":0,"visualContainers":[{"x":9.810935104752172,"y":0,"z":0,"width":1238.794072560041,"height":633.7864077669904,"config":{"name":"681899cb5aa4123aa916","layouts":[{"id":0,"position":{"x":9.810935104752172,"y":0,"z":0,"width":1238.794072560041,"height":633.7864077669904}}],"singleVisual":{"visualType":"CHARTICULATOR_VISUAL_MyVisual2D8730A9416EF4EC187A897D1A2D6224","projections":{"manufacturer":[{"queryRef":"vehicles.manufacturer"}],"crew":[{"queryRef":"Sum(vehicles.crew)"}],"vehicle_class":[{"queryRef":"vehicles.vehicle_class"}]},"prototypeQuery":{"Version":2,"From":[{"Name":"v","Entity":"vehicles"}],"Select":[{"Column":{"Expression":{"SourceRef":{"Source":"v"}},"Property":"manufacturer"},"Name":"vehicles.manufacturer"},{"Aggregation":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"v"}},"Property":"crew"}},"Function":0},"Name":"Sum(vehicles.crew)"},{"Column":{"Expression":{"SourceRef":{"Source":"v"}},"Property":"vehicle_class"},"Name":"vehicles.vehicle_class"}],"OrderBy":[{"Direction":2,"Expression":{"Aggregation":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"v"}},"Property":"crew"}},"Function":0}}}]},"drillFilterOtherVisuals":true,"hasDefaultSort":true,"objects":{"7vll1fhkz69":[{"properties":{"7vll1fhkz69_Symbol1_size":{"expr":{"Literal":{"Value":"60D"}}}}}]},"vcObjects":{"visualTooltip":[{"properties":{"type":{"expr":{"Literal":{"Value":"'Canvas'"}}},"section":{"expr":{"Literal":{"Value":"'ReportSection08065b70cc073a96d476'"}}},"transparency":{"expr":{"Literal":{"Value":"0D"}}}}}]}}},"filters":"[]"}],"config":{},"displayOption":1,"width":1280,"height":720}

**Comment by snapper911T** [comment]
fixed!
